name: whiskers

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run:
    uses: catppuccin/actions/.github/workflows/whiskers-check.yml@feat/working-directory
    with:
      working-directory: packages/catppuccin-starlight
      args: starlight.tera
    secrets: inherit
